---
- name: Arch post-deployment
  hosts: arch
  become_method: ansible.builtin.sudo

  vars_files:
    - ../inventory/group_vars/all/vault.yml
    - ../vars/bibata_cursor.yml
    - ../vars/alacritty.yml
    - ../vars/common_pkgs.yml
    - ../vars/firefox.yml
    - ../vars/golang.yml
    - ../vars/tmux.yml
    - ../vars/fish.yml
    - ../vars/swaywm.yml
    - ../vars/git.yml

  roles:
    - pluggero.upgrade
    - pluggero.common_pkgs
    - pluggero.nerdfonts
    - pluggero.bibata_cursor
    - pluggero.alacritty
    - pluggero.fish
    - pluggero.tmux
    - pluggero.docker
    - pluggero.neovim
    - pluggero.firefox
    - pluggero.rofi
    - pluggero.golang
    - pluggero.rustup
    - pluggero.user_setup
    - pluggero.yazi
    - pluggero.borgbackup
    - pluggero.swaywm
    - pluggero.satty
    - pluggero.wireshark
    - pluggero.git
    - pluggero.gpg
